### ISSUE TITLE
请问怎么把代码高亮的插件替换成enlighter

### ISSUE THREAD

**Issue by CJSoldier** [ruibaby/next-halo#10]

**Comment by ruibaby** [comment]
理论上把 prism 相关的引入去掉，然后引入 enlighter 就行了。

**Comment by CJSoldier** [comment]
> 理论上把 prism 相关的引入去掉，然后引入 enlighter 就行了。

我试着把原来引入prism的地方替换成enlighter。但是没成功。
[修改的地方](https://github.com/halo-dev/halo-theme-next/blob/master/layout/_partials/head.ftl#L48)

我修改成了下面这个样子：
```html
<#if post??>
    <link rel="stylesheet" type="text/css" href="${static!}/source/lib/enlighter/resources/EnlighterJS.min.css"/>
    <script type="text/javascript" src="${static!}/source/lib/enlighter/resources/EnlighterJS.min.js"></script>
</#if>
```

我看了enlighter的demo。引入js和css后，它的代码块是用`<pre>`包起来的，而且还要设置一个主题，就像这样：

```html
<pre data-enlighter-language="java" data-enlighter-theme="Atomic">
...
</pre>
```

不知道我引入的地方对不对，引入enlighter的js和css后还需要修改其他地方吗？

**Comment by CJSoldier** [comment]
抱歉问了一个傻问题。是因为enlighter没有初始化。
