### ISSUE TITLE
本地搜索开启后不可用

### ISSUE THREAD

**Issue by changhr2013** [ruibaby/next-halo#2]
在安装主题后，在主题设置中打开【本地搜索】，页面有搜索按钮显示，点击搜索按钮后窗口**一直为loading状态**，无法弹出搜索模态框，无法定位到问题缘由。

[搭建主题的网站链接](https://lovemengya.cn/)

**Comment by TEC-NINE-AI-2026** [comment]
> 在安装主题后，在主题设置中打开【本地搜索】，页面有搜索按钮显示，点击搜索按钮后窗口**一直为loading状态**，无法弹出搜索模态框，无法定位到问题缘由。
> 
> [搭建主题的网站链接](https://lovemengya.cn/)

根据https://github.com/theme-next/hexo-generator-searchdb依赖的README.md的说明，
需要安装hexo-generator-searchdb依赖，并将主题配置文件的local_search的enable设置为true即可。
```
npm install hexo-generator-searchdb --save
```

**Comment by changhr2013** [comment]
请问在哪个目录执行npm模块的安装？halo将本主题上传到后台后，主题文件位于/opt/halo/resources/templates/themes/next-halo/文件夹下，在这个目录下执行npm安装模块后搜索依旧不可用。

**Comment by TEC-NINE-AI-2026** [comment]
> 请问在哪个目录执行npm模块的安装？halo将本主题上传到后台后，主题文件位于/opt/halo/resources/templates/themes/next-halo/文件夹下，在这个目录下执行npm安装模块后搜索依旧不可用。

在hexo根目录执行即可。

**Comment by changhr2013** [comment]
这个主题不是用来集成halo的吗？使用这个主题需要在本地也搭建hexo吗？

**Comment by TEC-NINE-AI-2026** [comment]
> 这个主题不是用来集成halo的吗？使用这个主题需要在本地也搭建hexo吗？

不好意思，我看错了。README里面一看还是hexo
