### ISSUE TITLE
关于代码块发布后未渲染的bug

### ISSUE THREAD

**Issue by BennettChina** [ruibaby/next-halo#27]
\`\`类型代码块在后台编辑时可以渲染出底色，发布后没有任何效果。

后台编辑效果：

![image](https://user-images.githubusercontent.com/48208644/104307451-31e42000-550a-11eb-9552-c7339b853ff9.png)

发布后的效果
![image](https://user-images.githubusercontent.com/48208644/104307503-41fbff80-550a-11eb-9174-fef92f76c885.png)

Halo版本：`1.4.2`
数据库：`H2 1.4.196 (2017-06-10)`
运行模式：`production`
User Agent：`Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36`

主题：`Next-Pisces`

由于halo的源码实在看不懂(注释太少了)，因此希望有人可以解答怎么解决这个问题。

**Comment by ruibaby** [comment]
已修复。
