### ISSUE TITLE
1.4版本开启社交功能，导致首页打不开

### ISSUE THREAD

**Issue by fangxy926** [ruibaby/next-halo#3]
![image](https://user-images.githubusercontent.com/23739775/51966980-0f85a300-24a9-11e9-85b2-1c5bc4bab4ee.png)

![image](https://user-images.githubusercontent.com/23739775/51967028-3217bc00-24a9-11e9-8fee-be589a279b8e.png)

**Comment by ruibaby** [comment]
已解决。
