### ISSUE TITLE
侧边栏社交链接中，邮箱部分：图标判断语句缺少括号，导致只要配置邮箱就抛异常导致侧边栏渲染失败。

### ISSUE THREAD

**Issue by aLLeENSmith** [ruibaby/next-halo#5]
侧边栏社交链接中，邮箱部分：图标判断语句缺少括号，导致只要配置邮箱就抛异常导致侧边栏渲染失败。

相关文件：
- /layout/_macro/sidebar.ftl line:92

相关图片
![image](https://user-images.githubusercontent.com/31880062/52777845-afcdf100-307f-11e9-90a4-a1d3fa50bcc1.png)
![image](https://user-images.githubusercontent.com/31880062/52777715-65e50b00-307f-11e9-9b49-33a078059fea.png)

**Comment by ruibaby** [comment]
好的，非常感谢你的反馈。

**Comment by ruibaby** [comment]
已解决。
