### ISSUE TITLE
分类显示问题

### ISSUE THREAD

**Issue by CSM-MTBT** [ruibaby/next-halo#8]
部署了方式：docker
主题是最新的：2019.6.3
问题：在分类页面下总是显示暂无分类
例如：https://blog.computsystmed.com/categories/

**Comment by ruibaby** [comment]
已确认是主题的问题，马上修复。

**Comment by ruibaby** [comment]
已修复，更新 NexT 主题即可。

**Comment by CSM-MTBT** [comment]
谢谢。
